details/urls.py
from django.urls import path, include
from . import views

app_name = 'details'

urlpatterns = [
    path('', views.all_blogs, name="all_blogs"),
    path('<int:blog_id>/', views.specified, name="specified"),
    path('post/', views.postings, name="postings"),
]

translucers/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from main import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name="home"),
    path('contact/', views.contact, name="contact"),
    path('about/', views.about, name="about"),
    path('blogs/', include('details.urls')),
    path('reviews/', views.review, name="review"),
    path('reviewsreaders/', views.reviewreaders, name="reviewreaders"),
    path('charity/', views.charity, name="charity"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

details/models.py
from django.db import models
from ckeditor.fields import RichTextField

class Blogs(models.Model):
    featuring = models.CharField(max_length=100)
    title = models.CharField(max_length=300)
    content = RichTextField(blank=True)
    author = models.CharField(max_length=200)
    post_views = models.IntegerField(blank=True, null=True, default=0)
    time_valid = models.DateTimeField(auto_now_add=True, editable=False)
    time_arr = models.DateField(auto_now_add=True, editable=False)

    def __str__(self):
        return self.title + self.author
    

main/models.py
from django.db import models
from django.contrib import admin

#Create your models here.

class Contact(models.Model):
    name = models.CharField(max_length=100)
    email = models.CharField(max_length=150)
    phone = models.CharField(max_length=10)
    desc = models.TextField()
    not_a_bot = models.BooleanField(blank=True, default=True)

    def __str__(self):
        return self.name

class Testimonials(models.Model):
    name = models.CharField(max_length=200)
    score = models.CharField(max_length=3, blank=True)
    time = models.DateTimeField(auto_now_add=True)
    desc = models.TextField()
    usr_time = models.DateField(auto_now_add=True)

    
    def __str__(self):
        return self.name + ' ' + self.score


class AboutUs(models.Model):
    editor = models.CharField(max_length=200)
    posting = models.CharField(max_length=150)
    date_joined = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return F"{self.editor} - {self.posting}"

details/forms.py
from django.forms import ModelForm
from .models import Blogs

class BlogForms(ModelForm):
    class Meta:
        model = Blogs
        fields = ['featuring', 'title', 'content', 'author']

main/forms.py
from django.forms import ModelForm
from .models import Contact, Testimonials


class ContactForm(ModelForm):
    class Meta:
        model = Contact
        fields = ['name', 'email', 'phone', 'desc', 'not_a_bot']


class ReviewForm(ModelForm):
    class Meta:
        model = Testimonials
        fields = ['name', 'desc']

details/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import BlogForms
from operator import attrgetter
from .models import Blogs
from django.db.models import Q
# Create your views here.

#used  for complex q lookup not used as real views
def get_blog_queryset(query=None):
    queryset = []
    queries = query.split(" ")
    for q in queries:
        posts = Blogs.objects.filter(
            Q(title__icontains=q) |
            Q(content__icontains=q) |
            Q(featuring__icontains=q)
        ).distinct()

        for post in posts:
            queryset.append(post)
    return list(set(queryset))


def all_blogs(request):

    context = {}

    query = ""
    if request.GET:
        query = request.GET.get('q')
        context['query'] = str(query)

    blogposts = sorted(get_blog_queryset(query), key=attrgetter('time_valid'), reverse=True)
    context["all_blogs"] = blogposts
    # context = {
    #     "all_blogs": qs,
    # }

    return render(request, 'details/all_blogs.html', context)





def specified(request, blog_id):
    blog = get_object_or_404(Blogs, id=blog_id)

    blog_views = Blogs.objects.get(id=blog_id)
    blog_views.post_views += 1
    blog_views.save()

    context = {'views': blog_views, 'blog': blog}
    return render(request, 'details/detailed.html', context)
    

def postings(request):
    if request.method == "GET":
        context = {'form': BlogForms()}
        return render(request, 'details/postings.html', context)
    
    else:#i.e post
        try:
            form = BlogForms(request.POST)
            form.save()
            return redirect('home')
        
        except ValueError:
            context = {'form': BlogForms(), 'error': 'Hey! common fill the form completely'}
            return render(request, 'details/postings.html', context)
        else:
            pass#almost impossible to happen just abiding pep8 style of coding

main/views.py
from django.shortcuts import render, redirect
from .forms import ContactForm, ReviewForm
from .models import Contact, Testimonials, AboutUs
from details.models import Blogs
# Create your views here.

def home(request):
    
    total_blogs = Blogs.objects.all()
    contacted = Contact.objects.all()
    context = {"all_blogs": total_blogs, "contact": contacted}
    return render(request, 'main/home.html', context)

def contact(request):
    
    if request.method == "GET":
        
        context = {'form': ContactForm()}
        return render(request, 'main/contact.html', context)
    else:#if POST
        try:
            form = ContactForm(request.POST)
            form.save()
            return redirect('home')
        except ValueError:
            context = {'form': ContactForm(), 'error': "Hey look up the form..... you didn't make the cut"}
            return render(request, 'main/contact.html', context)


def about(request):
    about = AboutUs.objects.all()
    context = {"about": about}
    return render(request, 'main/about.html', context)


def review(request):
    if request.method=="GET":
        context={'form': ReviewForm()}
        return render(request, 'main/review.html', context)
    
    else:#i.e POST
        try:
            forms = ReviewForm(request.POST)
            forms.save()
            return redirect('reviewreaders')
        except ValueError:
            context={'error':'hey Buddy! your form did not make the cut, Please Try Again', 'forms': ReviewForm()}
            return render(request, 'main/review.html', context)
        else:#impossible to transpire
            pass


def reviewreaders(request):
    reviews = Testimonials.objects.order_by('-time')
    context={"reviews": reviews}
    return render(request, 'main/review_reader.html', context)

def charity(request):
    context = {}
    return render(request, 'main/charity.html', context)

templates/details/all_blogs.html
{% extends 'main/base.html' %}
{% block title %}Caliber: Blogs{% endblock %}

{% block blogs %}active{% endblock %}

{% block content %}


<div class="container my-5 py-5">

      <form class="d-flex" method="GET" action="{% url 'details:all_blogs' %}">
        <input class="form-control me-2" type="search" placeholder="Search Blogs" aria-label="Search" name='q' id="id_q" value="{{ query }}">
        <button class="btn btn-outline-light" type="submit" style="border: 2px solid">Search</button>
      </form>


{% if all_blogs %}
<h1 class="text-center pt-5 mb-3" style="color: white;font-size:4vw;">{{ all_blogs.count }} Boost Up.. We got some 😃, to get all the latest blogs search 'all'</h1>

{% for all_blog in all_blogs%}

<div class="card text-center my-5">

  <div class="card-header">
    {{ all_blog.featuring }}
  </div>
  <div class="card-body">
    <h5 class="card-title">{{ all_blog.title }}</h5>
    <p class="card-text px-5">{{ all_blog.content|striptags|truncatechars:200|safe }}</p>
    <a href="{% url 'details:specified' all_blog.id %}" ><button class="btn btn-outline-dark pt-2 pb-1" style="border: 2px solid"><h6>Read more</h6></button></a>
  </div>
  <div class="card-footer text-muted">
    {{ all_blog.time_valid }}
  </div>
</div>

  {% endfor %}

{% else %}
<div class="container my-5 py-5 text-center">
<h1 style="color: white;">Oops 😔  "{{query}}" sounds complicated... try something else</h1>
<h1 style="color: white;" class="mt-5 mb-0">Else make us aware of what are you trying to search: by posting testimonials, if not... contact us by giving your details and write a description about the results you are opting... Thanks for supporting</h1>
  <div class="text-center my-5">
  <a href="{% url 'contact' %}">
  <button class="btn btn-outline-light py-2 pt-3 px-4" style="border: 2px solid"><h5>Contact Us</h5></button></a>
  </div>
  <div class="text-center mt-4">
  <a href="{% url 'review' %}">
  <button class="btn btn-outline-light py-2 pt-3 px-4" style="border: 2px solid"><h5>Testimonials</h5></button></a>
  </div>

{% endif %}


</div>


</div>


{% comment %} <script type="text/javascript">
  document.getElementById("id_q").value = "{{query}}"
  {% comment %} using this script as sarch value doesnt work great with django
</script> {% endcomment %}


{% endblock %}

templates/details/detailed.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>Hello, world!</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>
  <body>

<style>
h1 {
  font-size: 5.9vw;
}
h2 {
  font-size: 3.0vh;
}
p {
  font-size: 2vmin;
}
</style>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

<div class="container my-5 py-2 text-center">





<h1 style="color:grey;size:3vw;">{{ blog.title }}</h1>
<hr class="my-4 mt-4">




<div class="card w-100 mt-3">
  <div class="card-body">
    <h4 class="card-text" style="size:8vw;">{{ blog.content|safe|linebreaks }}</h4>
  </div>
</div>

<h4 style="color:grey;size:4vw;" class="my-3">👁️ {{ views.post_views }}</h4>
<h4 style="color:grey;size:4vw;" class="my-3">Date Released: {{ views.time_valid }}</h4>
<h3 style="color:grey;size:4vw;" class="my-3">
By: {{ blog.author }}
</h3>
<a href="{% url 'details:all_blogs' %}" class="btn btn-primary">Go back</a>




</div>
  </body>
</html>

templates/details/postings.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">

    <title>Hello, world!</title>
  </head>
  <body>


    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js" integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js" integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc" crossorigin="anonymous"></script>
    -->

<div class="container my-5">

{% if error %}
<div class="alert alert-danger alert-dismissible fade show text-center" role="alert">
{{error}} 
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

{% endif %}

<form method="POST">{% csrf_token %}
  
 <div class="mb-3">
    <label for="featuring" class="form-label">Featuring</label>
    <input type="text" class="form-control" id="featuring" name="featuring" aria-describedby="emailHelp">
    <div id="emailHelp" class="form-text">ex=sports, politics, stocks, general awarness and etc..</div>
  </div>

  <div class="mb-3">
    <label for="title" class="form-label">Title</label>
    <input type="text" class="form-control" id="title" name = "title" aria-describedby="emailHelp">
    <div id="emailHelp" class="form-text">ex=skipper slips... will he miss</div>
  </div>

{{ form.content }}
{{ form.media }}


  <div class="mb-3 mt-3">
    <label for="author" class="form-label">Author</label>
    <input type="text" class="form-control" id="author" name="author" aria-describedby="emailHelp">
    <div id="emailHelp" class="form-text">ex=Shravan, John, Muhamad etc...</div>
  </div>

{% comment %} {{ form.as_p }}
{{ form.media }} {% endcomment %}

<button type="submit" class="btn btn-primary mt-3">Post</button>

</form>

</div>
  </body>
</html>

templates/main/about.html
{% extends 'main/base.html' %}



{% block title %}Caliber: AboutUs{% endblock %}

{% block about %}active{% endblock %}

{% block content %}

<div class="container mt-5 mb-0 py-5">
<h1 style="color: white;font-size:3vw;" class="my-5 text-center">Site Aired On :  April 25, Sunday</h1> 
<h1 style="color: white;font-size:5vw;" class="my-5 text-center">Our Editors</h1> 
<div style="background-color:#40E0D0; height:10px;"></div>
{% for editors in about %}
<div class="text-center">
<h1 class="pt-3 mb-3" style="color: white;font-size:3vw;"><br>{{ editors.editor }}</b></h1>
<h1 class="pt-3 mb-3" style="color: #40E0D0;font-size:3vw;"><br>{{ editors.posting }}</b></h1>
<h1 class="pt-3 mb-3" style="color: white;font-size:3vw;"><br>{{ editors.date_joined }}</b></h1>
<div style="background-color:#40E0D0; height:10px;"></div>
</div>
{% endfor %}

</div>

{% endblock %}

templates/main/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">

    <title>{% block title %}{% endblock %}</title>

<style>
#myBtn {
  
  position: fixed;
  bottom: 20px;
  right: 30px;
  z-index: 99;
  font-size: 20px;
  border: none;
  outline: none;
  background-color: #40E0D0;
  color: white;
  cursor: pointer;
  padding: 15px;
  border-radius: 50px;
}

</style>

  </head>
  <body class="text-justify-lg" style="background-color: black;">
  <button onclick="topFunction()" id="myBtn" title="Go to top"><b><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-up" viewBox="0 0 16 16">
  <path fill-rule="evenodd" d="M8 15a.5.5 0 0 0 .5-.5V2.707l3.146 3.147a.5.5 0 0 0 .708-.708l-4-4a.5.5 0 0 0-.708 0l-4 4a.5.5 0 1 0 .708.708L7.5 2.707V14.5a.5.5 0 0 0 .5.5z"/>
</svg></b></button>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js" integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js" integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc" crossorigin="anonymous"></script>
    -->

<script src="https://kit.fontawesome.com/yourcode.js" crossorigin="anonymous"></script>

{% comment %} <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top px-5">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'home' %}">Calliber</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a class="nav-link {% block home %}{% endblock %}" aria-current="page" href="{% url 'home' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% block about %}{% endblock %}" href="{% url 'about' %}">About Us</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% block blogs %}{% endblock %}" href="{% url 'details:all_blogs' %}">Blogs</a>
        </li>        
        <li class="nav-item">
          <a class="nav-link {% block contact %}{% endblock %}" href="{% url 'contact' %}">Contact Us</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% block testimonials %}{% endblock %}" href="{% url 'reviewreaders' %}">Testimonials</a>
        </li>
      </ul>
          
    </div>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav> {% endcomment %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top px-5">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'home' %}">Caliber</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link {% block home %}{% endblock %}" aria-current="page" href="{% url 'home' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% block about %}{% endblock %}" aria-current="page" href="{% url 'about' %}">About Us</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% block blogs %}{% endblock %}" aria-current="page" href="{% url 'details:all_blogs' %}">Blogs</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% block contact %}{% endblock %}" aria-current="page" href="{% url 'contact' %}">Contact Us</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% block testimonials %}{% endblock %}" aria-current="page" href="{% url 'reviewreaders' %}">Testimonials</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% block charity %}{% endblock %}" aria-current="page" href="{% url 'charity' %}">Charity</a>
        </li>



      </ul>


    </div>
  </div>
</nav>












{% comment %} <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ms-auto">
      <li class="nav-item active">
                <li class="nav-item">
          <a class="nav-link {% block home %}{% endblock %}" aria-current="page" href="{% url 'home' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% block about %}{% endblock %}" href="{% url 'about' %}">AboutUs</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% block blogs %}{% endblock %}" href="{% url 'details:all_blogs' %}">Blogs</a>
        </li>        
        <li class="nav-item">
          <a class="nav-link {% block contact %}{% endblock %}" href="{% url 'contact' %}">ContactUs</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% block testimonials %}{% endblock %}" href="{% url 'reviewreaders' %}">Testimonials</a>
        </li>
      </li>
    </ul>
  </div>
</nav> {% endcomment %}


{% block content%} {% endblock %}
<!-- Footer -->
<footer class="bg-dark text-center text-white bottom">
  <!-- Grid container -->
  <div class="container p-4">
    <!-- Section: Social media -->

    <!-- Section: Social media -->

    <!-- Section: Form -->
    <!-- Section: Form -->

    <!-- Section: Text -->
    <section class="mb-1 pb-4">
      <p class="h5">
        We work hard... We tire ourself to the most extreme.... Draining most of our stamina a day to render the best content available across the whole globe... do make us fell ecstatic by sharing this blog all-round your habitat... Thanks a lot -Caliber team 
      </p>
    </section>
    <!-- Section: Text -->

    <!-- Section: Links -->

    <!-- Section: Links -->
  </div>
  <!-- Grid container -->

  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    © 2020 Copyright:
    <a class="text-white" href="https://macromrit.pythonanywhere.com/" target="_blank">macromrit.pythonanywhere.com</a>
  </div>
  <!-- Copyright -->
</footer>
<!-- Footer -->

{% comment %} script for the topp rolling button {% endcomment %}
<script>
//Get the button
var mybutton = document.getElementById("myBtn");

// When the user scrolls down 20px from the top of the document, show the button
window.onscroll = function() {scrollFunction()};

function scrollFunction() {
  if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
    mybutton.style.display = "block";
  } else {
    mybutton.style.display = "none";
  }
}

// When the user clicks on the button, scroll to the top of the document
function topFunction() {
  document.body.scrollTop = 0;
  document.documentElement.scrollTop = 0;
}
</script>

  </body>
</html>

templates/main/charity.html
{% extends 'main/base.html' %}
{% load static %}
{% block charity %}active{% endblock %}
{% block content %}

<div class="container text-center my-5 py-5">
<h1 class="text-center pt-4 mb-4" style="color: white;font-size:10vw;">Feed <b style="color:#40E0D0;">Some.</b></h1>
<h1 class="text-center py-4 mb-4" style="color: white;font-size:10vw;">Feel <b style="color:#40E0D0;">More.</b></h1>
<h1 class="text-center py-4 mb-44" style="color: white;font-size:5vw;">Just Do Whatever You Could To Feed The <b style="color:#40E0D0;">Starving.</b></h1>
<h1 class="text-center py-4 mb-4" style="color: white;font-size:5vw;">Donate Funds By Using The QR Code Given Below</b></h1>
<img src="{% static "main/amma_donation.jpg" %}" class="img-fluid" alt="amms_qr_code">
<h1 class="text-center py-4 mb-4 mt-3" style="color: white;font-size:5vw;">Else Use UPI : amma@dlb To Donate</b></h1>
<h1 class="text-center py-4 mb-4" style="color: white;font-size:10vw;">We Appreciate Your <b style="color:#40E0D0;">Contrbution.</b></h1>
<h1 class="text-center pt-4 mb-2" style="color: white;font-size:5vw;">For More Details Visit: <a href="https://www.amritapuri.org/donate" target="_blank"></b></h1>
<br>
<button class="btn btn-outline-light" style="border: 2px solid" ><h1>www.amritapuri.org</h1></button></a>
</div>

{% endblock %}